import json
from pathlib import Path

import pandas as pd

from src.models.recommend import apply_priority_prefix, determine_recommendation, recommend_action_for_customer

MEDIAN_CHARGES = 70.0

# Meridian Wireless: a real self-registered tenant. Since Stage 2b
# (src/models/tenant_training.py's _run_optional_modules()) segment_model.pkl/
# anomaly_model.pkl are now trained unconditionally for every tenant - only
# CLV genuinely stays missing here (no clv_column was mapped for Meridian's
# real upload). Real artifacts, not mocks, so this test exercises the
# exact same code path production hits for a CLV-only-missing tenant.
MERIDIAN_MODEL_DIR = "models/meridian-wireless"
MERIDIAN_DATA_PATH = "data/tenant_uploads/meridian-wireless.csv"
MERIDIAN_TEST_CUSTOMER_ID = "MW-49541-DFWC"


def _first_real_telco_test_split_customer_id() -> str:
    """Resolves a real customerID that's actually in models/v1's CURRENT
    test split, rather than hardcoding one - split_indices.json is
    regenerated by every real retrain (e.g. src/models/train.py's
    hyperparameter tuning), so a hardcoded ID silently goes stale the
    first time anyone retrains Telco with a different split-affecting
    change, exactly as one did here (models/v1/split_indices.json had not
    actually been regenerated in a long time before this session, and the
    previously-hardcoded ID's split membership was stale)."""
    split_info = json.loads((Path("models") / "v1" / "split_indices.json").read_text(encoding="utf-8"))
    df = pd.read_csv("data/raw/telco.csv")
    return df.loc[split_info["test_idx"][0], "customerID"]


def test_rule_a_contract_driver_high_charges_recommends_discount():
    result = determine_recommendation(
        top_feature_names=["Contract", "tenure"],
        monthly_charges=100.0,  # above median
        monthly_charges_median=MEDIAN_CHARGES,
        churn_probability=0.9,
        is_anomaly=False,
        is_highest_risk_segment=False,
    )
    assert result["action"] == "Offer a discount or loyalty pricing to reduce price sensitivity"
    assert "Contract" in result["triggered_by"]


def test_rule_b_contract_driver_low_charges_recommends_contract_upgrade():
    result = determine_recommendation(
        top_feature_names=["Contract", "OnlineSecurity"],
        monthly_charges=30.0,  # below median
        monthly_charges_median=MEDIAN_CHARGES,
        churn_probability=0.5,
        is_anomaly=False,
        is_highest_risk_segment=False,
    )
    assert result["action"] == (
        "Offer a contract upgrade incentive (e.g. waived fee for switching to a longer contract)"
    )
    assert "Contract" in result["triggered_by"]


def test_rule_c_tenure_driver_high_churn_recommends_onboarding_support():
    result = determine_recommendation(
        top_feature_names=["tenure", "MonthlyCharges"],  # no Contract - rules a/b don't apply
        monthly_charges=50.0,
        monthly_charges_median=MEDIAN_CHARGES,
        churn_probability=0.75,  # > 0.6
        is_anomaly=False,
        is_highest_risk_segment=False,
    )
    assert result["action"] == "Assign priority onboarding support"
    assert "tenure" in result["triggered_by"]


def test_rule_d_anomaly_not_highest_risk_recommends_manual_review():
    result = determine_recommendation(
        top_feature_names=["OnlineSecurity", "PaymentMethod"],  # no Contract, no tenure
        monthly_charges=50.0,
        monthly_charges_median=MEDIAN_CHARGES,
        churn_probability=0.4,  # not > 0.6, so rule c doesn't apply
        is_anomaly=True,
        is_highest_risk_segment=False,
    )
    assert result["action"] == "Review manually — unusual profile, standard playbook may not apply"
    assert "anomaly_flag" in result["triggered_by"]


def test_rule_e_low_churn_probability_recommends_no_action():
    result = determine_recommendation(
        top_feature_names=["OnlineSecurity", "PaymentMethod"],
        monthly_charges=50.0,
        monthly_charges_median=MEDIAN_CHARGES,
        churn_probability=0.1,  # < 0.3
        is_anomaly=False,
        is_highest_risk_segment=False,
    )
    assert result["action"] == "No action needed — monitor as part of regular review"


def test_rule_f_fallback_recommends_standard_outreach():
    result = determine_recommendation(
        top_feature_names=["OnlineSecurity", "PaymentMethod"],
        monthly_charges=50.0,
        monthly_charges_median=MEDIAN_CHARGES,
        churn_probability=0.45,  # not < 0.3, not > 0.6, no Contract/tenure/anomaly
        is_anomaly=False,
        is_highest_risk_segment=False,
    )
    assert result["action"] == "Standard retention outreach — no dominant driver identified"
    assert result["triggered_by"] == []


def test_anomaly_flagged_but_in_highest_risk_segment_does_not_trigger_rule_d():
    # is_highest_risk_segment=True means rule d's "not in highest-risk segment"
    # condition fails, so it should fall through to a later rule instead.
    result = determine_recommendation(
        top_feature_names=["OnlineSecurity"],
        monthly_charges=50.0,
        monthly_charges_median=MEDIAN_CHARGES,
        churn_probability=0.1,
        is_anomaly=True,
        is_highest_risk_segment=True,
    )
    assert result["action"] != "Review manually — unusual profile, standard playbook may not apply"
    assert result["action"] == "No action needed — monitor as part of regular review"


def test_priority_prefix_applied_only_when_clv_top20():
    assert apply_priority_prefix("Some action", is_clv_top20=True) == "PRIORITY: Some action"
    assert apply_priority_prefix("Some action", is_clv_top20=False) == "Some action"


def test_recommend_for_clv_only_missing_tenant_does_not_crash_and_reports_reduced_coverage():
    """Meridian has real segment_model.pkl/anomaly_model.pkl (Stage 2b
    trains these unconditionally) but no CLV data - recommend_action_for_customer
    must still return a real recommendation, not crash, and its based_on
    field must honestly reflect exactly what's actually available (segment/
    anomaly present, clv absent) rather than silently looking like Telco's
    full-signal result or silently dropping the signals it DOES have."""
    result = recommend_action_for_customer(
        MERIDIAN_TEST_CUSTOMER_ID,
        model_dir=MERIDIAN_MODEL_DIR,
        data_path=MERIDIAN_DATA_PATH,
        clv_data_path=None,
    )

    assert result["customer_id"] == MERIDIAN_TEST_CUSTOMER_ID
    assert isinstance(result["recommended_action"], str) and result["recommended_action"]
    assert result["based_on"] == ["churn_probability", "segment", "anomaly"]
    assert result["is_priority"] is False  # no CLV data - can never be top-20% priority


def test_recommend_for_full_signal_telco_tenant_reports_full_coverage():
    """Telco has every artifact (segment/anomaly/CLV) - based_on must
    reflect that nothing was skipped, confirming the degradation logic
    doesn't accidentally reduce coverage for a tenant that has everything."""
    test_customer_id = _first_real_telco_test_split_customer_id()
    result = recommend_action_for_customer(
        test_customer_id,
        model_dir="models/v1",
        data_path="data/raw/telco.csv",
        clv_data_path="data/raw/telco_enriched.csv",
    )
    assert result["based_on"] == ["churn_probability", "clv", "segment", "anomaly"]


# --- Regression: the third confirmed real instance of this project's
# recurring hardcoded-Telco-column bug (Meridian's action-queue/alerts,
# Aurora's business-impact, now recommend_action_for_customer() itself -
# /api/action-queue 500'd with the same "Missing required columns:
# ['Churn', 'MonthlyCharges', 'customerID']" shape). ---

AURORA_MODEL_DIR = "models/aurora-streaming"
AURORA_DATA_PATH = "data/tenant_uploads/aurora-streaming.csv"


def _first_real_aurora_test_split_customer_id() -> str:
    """Same staleness-avoidance reasoning as
    _first_real_telco_test_split_customer_id() above - resolves a real
    customer_id from Aurora's CURRENT test split rather than hardcoding one."""
    split_info = json.loads((Path(AURORA_MODEL_DIR) / "split_indices.json").read_text(encoding="utf-8"))
    df = pd.read_csv(AURORA_DATA_PATH)
    return df.loc[split_info["test_idx"][0], "customer_id"]


def test_aurora_recommend_action_loads_with_genuinely_different_column_names():
    """End-to-end against Aurora's real trained artifacts - id/target/
    revenue/clv columns (customer_id/churned/monthly_fee/
    lifetime_value_estimate) share NOT ONE literal name with Telco's
    (customerID/Churn/MonthlyCharges/CLTV), and Aurora has no
    duration_column mapped at all. Used to crash outright; must now
    return a real recommendation."""
    test_customer_id = _first_real_aurora_test_split_customer_id()
    result = recommend_action_for_customer(
        test_customer_id,
        model_dir=AURORA_MODEL_DIR,
        data_path=AURORA_DATA_PATH,
        clv_data_path=AURORA_DATA_PATH,  # self-registered tenants: same file as data_path
    )

    assert result["customer_id"] == test_customer_id
    assert isinstance(result["recommended_action"], str) and result["recommended_action"]
    # Aurora's clv/segments/anomalies modules all passed their own sanity
    # gates (see this session's training report) - full coverage minus
    # nothing, same shape as the full-signal Telco assertion above.
    assert result["based_on"] == ["churn_probability", "clv", "segment", "anomaly"]


def test_recommend_action_for_a_freshly_trained_tenant_with_non_telco_column_names(tmp_path):
    """Self-contained variant (trains its own tiny synthetic tenant in
    tmp_path) so this specific guard runs anywhere - CI included - rather
    than only on a dev machine that happens to already have a real
    self-registered tenant's (gitignored, not committed) local artifacts
    sitting around. Mirrors
    tests/test_business_impact.py's equivalent synthetic regression test."""
    import numpy as np

    from src.config import load_config
    from src.models.anomaly import detect_anomalies
    from src.models.clv import train_clv_model
    from src.models.segment import run_segmentation
    from src.models.train import train_model

    ROOT = Path(__file__).resolve().parents[1]
    CONFIG_PATH = ROOT / "config" / "config.yaml"

    rng = np.random.default_rng(11)
    n = 320
    tenure_like = rng.integers(0, 60, size=n)
    fee = np.round(rng.normal(20, 5, size=n).clip(5, 40), 2)
    plan = rng.choice(["Alpha", "Beta"], size=n)
    logit = -0.5 - 0.02 * tenure_like + 0.4 * (plan == "Alpha") + rng.normal(0, 0.6, size=n)
    left = np.where(rng.random(n) < 1 / (1 + np.exp(-logit)), "Yes", "No")
    value_score = np.round(
        tenure_like * fee * rng.lognormal(0, 0.4, size=n) + rng.normal(0, 20, size=n), 2
    ).clip(0, None)

    df = pd.DataFrame(
        {
            "acct_id": [f"A{i:04d}" for i in range(n)],
            "months_active": tenure_like,
            "fee_amount": fee,
            "plan_name": plan,
            "value_score": value_score,
            "left": left,
        }
    )
    data_path = tmp_path / "synthetic.csv"
    df.to_csv(data_path, index=False)

    tenant_config = {
        "id_column": "acct_id",
        "target_column": "left",
        "target_positive_value": "Yes",
        "revenue_column": "fee_amount",
        "clv_column": "value_score",
        "tuning_enabled": False,  # keep this test fast - not what's under test here
    }
    model_dir = tmp_path / "model"
    train_model(data_path, CONFIG_PATH, output_dir=model_dir, tenant_config=tenant_config)
    # Segment/anomaly artifacts are what make has_segment/has_anomaly True
    # in _population_context() - train them too, same as Stage 2b does for
    # a real self-registered tenant, so this test exercises the full-coverage
    # path, not just the graceful-degradation one already covered above.
    run_segmentation(model_dir=model_dir, data_path=data_path, tenant_config=tenant_config)
    detect_anomalies(model_dir=model_dir, data_path=data_path, tenant_config=tenant_config)
    train_clv_model(model_dir=model_dir, data_path=data_path, tenant_config=tenant_config)

    split_info = json.loads((model_dir / "split_indices.json").read_text(encoding="utf-8"))
    test_customer_id = df.loc[split_info["test_idx"][0], "acct_id"]

    result = recommend_action_for_customer(
        test_customer_id,
        model_dir=model_dir,
        data_path=data_path,
        clv_data_path=data_path,
    )
    assert result["customer_id"] == test_customer_id
    assert isinstance(result["recommended_action"], str) and result["recommended_action"]
    assert result["based_on"] == ["churn_probability", "clv", "segment", "anomaly"]
