"""Generates 5 distinct, clean, live-demo-ready company CSVs - v2 batch.

See data/live_demo_v2/README.md for each company's backstory, row count,
and column-to-role mapping. Distinct from BOTH data/test_onboarding_samples/
(deliberately messy - thin data, confusing names, data-quality rot, a
malicious upload) and data/live_demo/ (the first 6-company live-demo batch,
generated by scripts/generate_live_demo_batch.py) - this batch reuses that
first batch's "every company gets the full mappable-role set, genuine churn
structure, no injected data-quality issues" design, but is purpose-built to
stress-test the tenant_config column-name generalization work (business_
impact.py/prioritize.py/backtest.py/scenario.py/recommend.py/timeline.py -
see docs/ADDING_A_TENANT.md's recurring-lessons section) by deliberately
varying NAMING CONVENTION far more aggressively than the first batch, which
used ordinary snake_case/space-separated names throughout:

  1. Vantage Legal Services      - verbose, human-readable column names
     ("Client Reference Number", "Months as Client", ...)
  2. Ridgeline Outdoor Gear Club - snake_case abbreviations
     ("cust_id", "mo_active", "sub_fee", ...)
  3. Beacon Home Security        - camelCase
     ("customerId", "monthsActive", "monthlyFee", ...)
  4. Thornfield Pet Insurance    - inconsistent/mixed casing PLUS a
     genuinely non-binary target ("Status": Active/Lapsed, not Yes/No) -
     the one company here that stress-tests target_positive_value
     inference (src/models/tenant_training.py's
     _tenant_config_from_mapping(): minority-class inference), not just
     column-name matching.
  5. Meadowbrook Senior Living   - column names with numbers/special
     characters mixed in ("Resident_ID#", "Tenure(mo)", "Monthly_Fee$", ...)

Every company still gets the full mappable-role set (id/target/revenue/
duration/segment-hazard-driver-categorical/clv) plus 8 additional feature
columns (comfortably above the 6+ minimum) with real, non-trivial variance
and genuine churn structure - same quality bar and same THE-SEGMENT-COLUMN-
DOMINANCE-TRICK alphabetical-order convention as scripts/
generate_live_demo_batch.py (see that script's own module docstring for the
full explanation: survival.py auto-derives segment_feature_column from
whichever categorical's hazard ratio deviates furthest from 1.0, and
categorical levels are encoded in sorted-name order, so a tier/plan-style
column's real risk signal only survives cleanly when its alphabetical order
already matches its true risk order).

This script does NOT register, upload, map, or train any of these -
generate-and-save only, exactly like scripts/generate_live_demo_batch.py
(see this project's own live-demo workflow: register/upload/map/validate/
train is done live, by a person, choosing which company to use).

Deterministic: every random draw goes through a single seeded
numpy.random.Generator (SEED), so re-running this script reproduces
byte-identical output.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

SEED = 42
OUT_DIR = Path(__file__).resolve().parent.parent / "data" / "live_demo_v2"


def _ids(n: int, prefix: str, width: int = 5) -> list[str]:
    return [f"{prefix}-{i:0{width}d}" for i in range(1, n + 1)]


def _tiered_numeric(rng: np.random.Generator, tier: np.ndarray, tier_order: list[str], params: dict) -> np.ndarray:
    """params: {tier_name: (mean, sd, lo, hi)} - independent noisy draw per
    tier band, not a bare lookup (every company's revenue column has real
    within-tier variance). Same helper as scripts/generate_live_demo_batch.py."""
    out = np.empty(len(tier))
    for t in tier_order:
        mean, sd, lo, hi = params[t]
        mask = tier == t
        out[mask] = np.round(rng.normal(mean, sd, size=int(mask.sum())).clip(lo, hi), 2)
    return out


def _make_clv(
    rng: np.random.Generator,
    duration: np.ndarray,
    revenue: np.ndarray,
    bonus: np.ndarray,
    mult_sigma: float = 0.45,
    additive_noise_sd: float = 60.0,
) -> np.ndarray:
    """Genuine, noisy CLV-like column - real signal from duration*revenue
    PLUS substantial multiplicative + additive noise, deliberately NOT a
    near-deterministic function of duration/revenue (the exact leak shape
    src/models/survival.py's DURATION_LEAKAGE_AUTO_DETECT_THRESHOLD exists
    to catch). Every caller's correlation is checked in __main__ below."""
    noise_factor = rng.lognormal(mean=0.0, sigma=mult_sigma, size=len(duration))
    value = duration * revenue * noise_factor + bonus + rng.normal(0, additive_noise_sd, size=len(duration))
    return np.round(value.clip(0, None), 2)


def _bernoulli(rng: np.random.Generator, logit: np.ndarray) -> np.ndarray:
    p = 1.0 / (1.0 + np.exp(-logit))
    return rng.random(len(logit)) < p


# ---------------------------------------------------------------------------
# 1. Vantage Legal Services - legal/professional services retainer clients.
#    VERBOSE, human-readable column names.
# ---------------------------------------------------------------------------

VANTAGE_TIERS = ["Basic Retainer", "Premier Retainer", "Signature Retainer"]  # alphabetical == decreasing risk
VANTAGE_TIER_WEIGHTS = [0.40, 0.38, 0.22]
VANTAGE_FEE_PARAMS = {
    "Basic Retainer": (850.0, 130.0, 500.0, 1300.0),
    "Premier Retainer": (2100.0, 300.0, 1400.0, 3200.0),
    "Signature Retainer": (4800.0, 700.0, 3200.0, 7500.0),
}


def make_vantage_legal(rng: np.random.Generator, n: int = 1500) -> pd.DataFrame:
    tier = rng.choice(VANTAGE_TIERS, size=n, p=VANTAGE_TIER_WEIGHTS)
    months_as_client = rng.integers(0, 85, size=n)
    monthly_retainer_fee = _tiered_numeric(rng, tier, VANTAGE_TIERS, VANTAGE_FEE_PARAMS)
    practice_area = rng.choice(
        ["Corporate", "Family", "Real Estate", "Litigation", "Estate Planning"],
        size=n, p=[0.28, 0.20, 0.18, 0.20, 0.14],
    )
    case_load_estimate = rng.poisson(2.4, size=n).clip(0, 15)
    matters_filed = rng.poisson(1.3, size=n).clip(0, 12)
    contact_method = rng.choice(["Email", "Phone", "Client Portal"], size=n, p=[0.52, 0.28, 0.20])
    dedicated_attorney = rng.random(n) < (0.20 + 0.45 * (tier == "Signature Retainer") + 0.18 * (tier == "Premier Retainer"))
    avg_response_hours = np.round(rng.gamma(shape=2.2, scale=5.0, size=n).clip(0.5, 72), 1)
    referral_source = rng.choice(["Referral", "Web Search", "Advertisement", "Repeat Client"], size=n, p=[0.40, 0.26, 0.14, 0.20])
    billing_disputes = rng.poisson(0.35, size=n).clip(0, 8)
    uses_client_portal = rng.random(n) < 0.46

    logit = (
        -1.55
        + 1.60 * (tier == "Basic Retainer")
        - 1.05 * (tier == "Signature Retainer")
        + 0.55 * (months_as_client < 6)
        - 0.35 * (months_as_client >= 36)
        - 0.55 * dedicated_attorney
        + 0.16 * billing_disputes
        + 0.012 * avg_response_hours
        - 0.14 * uses_client_portal
        - 0.05 * case_load_estimate
        + rng.normal(0, 0.55, size=n)
    )
    left_firm = np.where(_bernoulli(rng, logit), "Yes", "No")

    ltv = _make_clv(
        rng, months_as_client, monthly_retainer_fee,
        bonus=180.0 * matters_filed + np.where(dedicated_attorney, 900.0, 0.0),
        additive_noise_sd=450.0,
    )

    return pd.DataFrame(
        {
            "Client Reference Number": _ids(n, "VLS"),
            "Months as Client": months_as_client,
            "Service Tier": tier,
            "Monthly Retainer Fee": monthly_retainer_fee,
            "Primary Practice Area": practice_area,
            "Case Load Estimate": case_load_estimate,
            "Number of Matters Filed": matters_filed,
            "Preferred Contact Method": contact_method,
            "Has Dedicated Attorney": np.where(dedicated_attorney, "Yes", "No"),
            "Average Response Time Hours": avg_response_hours,
            "Referral Source": referral_source,
            "Billing Dispute Count": billing_disputes,
            "Uses Client Portal": np.where(uses_client_portal, "Yes", "No"),
            "Estimated Lifetime Client Value": ltv,
            "Left Firm": left_firm,
        }
    )


# ---------------------------------------------------------------------------
# 2. Ridgeline Outdoor Gear Club - outdoor/retail subscription box.
#    snake_case ABBREVIATIONS.
# ---------------------------------------------------------------------------

RIDGELINE_TIERS = ["core", "plus", "summit"]  # alphabetical == decreasing risk
RIDGELINE_TIER_WEIGHTS = [0.42, 0.36, 0.22]
RIDGELINE_FEE_PARAMS = {"core": (24.99, 3.0, 15.0, 35.0), "plus": (44.99, 5.0, 32.0, 60.0), "summit": (74.99, 9.0, 55.0, 100.0)}


def make_ridgeline_outdoor(rng: np.random.Generator, n: int = 2800) -> pd.DataFrame:
    tier = rng.choice(RIDGELINE_TIERS, size=n, p=RIDGELINE_TIER_WEIGHTS)
    mo_active = rng.integers(0, 61, size=n)
    sub_fee = _tiered_numeric(rng, tier, RIDGELINE_TIERS, RIDGELINE_FEE_PARAMS)
    gear_cat = rng.choice(["camping", "hiking", "climbing", "fishing"], size=n, p=[0.32, 0.30, 0.20, 0.18])
    boxes_skip = rng.poisson(1.2, size=n).clip(0, 12)
    ref_cnt = rng.poisson(0.55, size=n).clip(0, 10)
    app_use = rng.random(n) < 0.61
    avg_rating = np.round(rng.normal(4.0, 0.75, size=n).clip(1.0, 5.0), 1)
    pay_meth = rng.choice(["card", "paypal", "bnpl"], size=n, p=[0.58, 0.30, 0.12])
    loyalty_pts = rng.gamma(shape=2.0, scale=160.0, size=n).clip(0, None).round().astype(int)
    gift_sub = rng.random(n) < 0.08

    logit = (
        -0.80
        + 1.45 * (tier == "core")
        - 0.85 * (tier == "summit")
        + 0.50 * (mo_active < 4)
        - 0.05 * boxes_skip * -1  # placeholder kept explicit below; real term next line
        + 0.16 * boxes_skip
        - 0.18 * ref_cnt
        - 0.35 * gift_sub
        - 0.16 * app_use
        - 0.10 * (avg_rating - 3.0)
        + rng.normal(0, 0.55, size=n)
    )
    churn = np.where(_bernoulli(rng, logit), "yes", "no")

    ltv = _make_clv(rng, mo_active, sub_fee, bonus=6.5 * ref_cnt + 0.4 * loyalty_pts)

    return pd.DataFrame(
        {
            "cust_id": _ids(n, "RID"),
            "mo_active": mo_active,
            "box_tier": tier,
            "sub_fee": sub_fee,
            "gear_cat": gear_cat,
            "boxes_skip": boxes_skip,
            "ref_cnt": ref_cnt,
            "app_use": np.where(app_use, "yes", "no"),
            "avg_rating": avg_rating,
            "pay_meth": pay_meth,
            "loyalty_pts": loyalty_pts,
            "gift_sub": np.where(gift_sub, "yes", "no"),
            "ltv_est": ltv,
            "churn": churn,
        }
    )


# ---------------------------------------------------------------------------
# 3. Beacon Home Security - home security monitoring subscription.
#    camelCase.
# ---------------------------------------------------------------------------

BEACON_TIERS = ["Basic", "Premium", "Standard"]  # alphabetical == decreasing risk
BEACON_TIER_WEIGHTS = [0.34, 0.24, 0.42]
BEACON_FEE_PARAMS = {"Basic": (19.99, 2.5, 12.0, 28.0), "Premium": (54.99, 6.0, 40.0, 75.0), "Standard": (34.99, 4.0, 25.0, 48.0)}


def make_beacon_security(rng: np.random.Generator, n: int = 2000) -> pd.DataFrame:
    tier = rng.choice(BEACON_TIERS, size=n, p=BEACON_TIER_WEIGHTS)
    months_active = rng.integers(0, 73, size=n)
    monthly_fee = _tiered_numeric(rng, tier, BEACON_TIERS, BEACON_FEE_PARAMS)
    monitoring_type = rng.choice(["Professional", "Self-Monitored", "Hybrid"], size=n, p=[0.48, 0.30, 0.22])
    num_sensors = rng.poisson(4.5, size=n).clip(1, 20)
    has_camera = rng.random(n) < 0.64
    alarm_triggers_ytd = rng.poisson(1.6, size=n).clip(0, 20)
    mobile_app_active = rng.random(n) < 0.72
    contract_length_months = rng.choice([0, 12, 24, 36], size=n, p=[0.22, 0.35, 0.28, 0.15])
    install_type = rng.choice(["DIY", "Professional"], size=n, p=[0.40, 0.60])
    support_calls_ytd = rng.poisson(1.1, size=n).clip(0, 15)

    logit = (
        -1.20
        + 1.50 * (tier == "Basic")
        - 0.85 * (tier == "Premium")
        + 0.55 * (months_active < 6)
        - 0.30 * (months_active >= 36)
        - 0.010 * contract_length_months
        + 0.14 * alarm_triggers_ytd
        + 0.11 * support_calls_ytd
        - 0.20 * has_camera
        - 0.16 * mobile_app_active
        + rng.normal(0, 0.55, size=n)
    )
    cancelled = np.where(_bernoulli(rng, logit), "Yes", "No")

    ltv = _make_clv(rng, months_active, monthly_fee, bonus=25.0 * num_sensors + np.where(has_camera, 60.0, 0.0))

    return pd.DataFrame(
        {
            "customerId": _ids(n, "BHS"),
            "monthsActive": months_active,
            "planTier": tier,
            "monthlyFee": monthly_fee,
            "monitoringType": monitoring_type,
            "numSensors": num_sensors,
            "hasCamera": np.where(has_camera, "Yes", "No"),
            "alarmTriggersYtd": alarm_triggers_ytd,
            "mobileAppActive": np.where(mobile_app_active, "Yes", "No"),
            "contractLengthMonths": contract_length_months,
            "installType": install_type,
            "supportCallsYtd": support_calls_ytd,
            "estimatedValue": ltv,
            "cancelled": cancelled,
        }
    )


# ---------------------------------------------------------------------------
# 4. Thornfield Pet Insurance - pet insurance.
#    INCONSISTENT/MIXED casing, some deliberately ambiguous names, and a
#    genuinely non-binary target ("Active"/"Lapsed", not "Yes"/"No").
# ---------------------------------------------------------------------------

THORNFIELD_TIERS = ["Basic Accident", "Comprehensive", "Wellness Plus"]  # alphabetical == decreasing risk
THORNFIELD_TIER_WEIGHTS = [0.40, 0.38, 0.22]
THORNFIELD_PREMIUM_PARAMS = {
    "Basic Accident": (22.0, 4.0, 12.0, 35.0),
    "Comprehensive": (48.0, 8.0, 32.0, 70.0),
    "Wellness Plus": (78.0, 12.0, 55.0, 115.0),
}


def make_thornfield_pet_insurance(rng: np.random.Generator, n: int = 1800) -> pd.DataFrame:
    coverage_type = rng.choice(THORNFIELD_TIERS, size=n, p=THORNFIELD_TIER_WEIGHTS)
    policy_age_mo = rng.integers(0, 61, size=n)
    premium = _tiered_numeric(rng, coverage_type, THORNFIELD_TIERS, THORNFIELD_PREMIUM_PARAMS)
    pet_species = rng.choice(["Dog", "Cat", "Other"], size=n, p=[0.58, 0.36, 0.06])
    pet_age = rng.integers(0, 16, size=n)
    vet_visits_ytd = rng.poisson(2.1, size=n).clip(0, 15)
    multi_pet_household = rng.random(n) < 0.28
    claims_filed = rng.poisson(0.8, size=n).clip(0, 10)
    auto_renew = rng.random(n) < 0.66
    discount_applied = rng.random(n) < 0.31
    zip_region = rng.choice(["Urban", "Suburban", "Rural"], size=n, p=[0.42, 0.40, 0.18])

    logit = (
        -1.35
        + 1.55 * (coverage_type == "Basic Accident")
        - 0.90 * (coverage_type == "Wellness Plus")
        + 0.55 * (policy_age_mo < 6)
        - 0.30 * (policy_age_mo >= 30)
        - 0.60 * auto_renew
        - 0.14 * discount_applied
        + 0.10 * claims_filed
        - 0.05 * vet_visits_ytd
        - 0.12 * multi_pet_household
        + rng.normal(0, 0.55, size=n)
    )
    # A genuinely non-binary-looking target: "Active"/"Lapsed", not "Yes"/
    # "No" - stress-tests target_positive_value inference (minority-class,
    # not a hardcoded literal) rather than just column-name matching.
    status = np.where(_bernoulli(rng, logit), "Lapsed", "Active")

    ltv = _make_clv(rng, policy_age_mo, premium, bonus=40.0 * claims_filed + np.where(auto_renew, 120.0, 0.0))

    return pd.DataFrame(
        {
            "PolicyID": _ids(n, "TPI"),
            "policy_age_mo": policy_age_mo,
            "Coverage Type": coverage_type,
            "PREMIUM": premium,
            "Pet_Species": pet_species,
            "petAge": pet_age,
            "VET_VISITS_YTD": vet_visits_ytd,
            "Multi_pet_Household": np.where(multi_pet_household, "Yes", "No"),
            "claimsFiled": claims_filed,
            "AutoRenew": np.where(auto_renew, "Yes", "No"),
            "discount_applied": np.where(discount_applied, "Yes", "No"),
            "ZIPRegion": zip_region,
            "est_lifetime_val": ltv,
            "Status": status,
        }
    )


# ---------------------------------------------------------------------------
# 5. Meadowbrook Senior Living - subscription/membership senior living
#    community services. Column names with NUMBERS/SPECIAL CHARACTERS
#    mixed in.
# ---------------------------------------------------------------------------

MEADOWBROOK_TIERS = ["Independent Living", "Memory Care", "Skilled Nursing"]  # alphabetical == decreasing risk
MEADOWBROOK_TIER_WEIGHTS = [0.46, 0.24, 0.30]
MEADOWBROOK_FEE_PARAMS = {
    "Independent Living": (2400.0, 300.0, 1600.0, 3400.0),
    "Memory Care": (5200.0, 600.0, 3800.0, 7200.0),
    "Skilled Nursing": (6800.0, 800.0, 5000.0, 9500.0),
}


def make_meadowbrook_senior_living(rng: np.random.Generator, n: int = 1000) -> pd.DataFrame:
    care_level = rng.choice(MEADOWBROOK_TIERS, size=n, p=MEADOWBROOK_TIER_WEIGHTS)
    tenure_mo = rng.integers(0, 97, size=n)
    monthly_fee = _tiered_numeric(rng, care_level, MEADOWBROOK_TIERS, MEADOWBROOK_FEE_PARAMS)
    room_type = rng.choice(["Studio", "1BR", "2BR", "Suite"], size=n, p=[0.30, 0.34, 0.24, 0.12])
    meals_included = rng.choice([1, 2, 3], size=n, p=[0.18, 0.34, 0.48])
    family_visits_month = rng.poisson(2.6, size=n).clip(0, 20)
    has_companion_pet = rng.random(n) < 0.14
    activity_participation_pct = rng.integers(0, 101, size=n)
    emergency_calls_ytd = rng.poisson(1.4, size=n).clip(0, 20)
    distance_to_family_mi = np.round(rng.gamma(shape=1.8, scale=25.0, size=n).clip(1, 400), 1)
    satisfaction_score = rng.integers(1, 11, size=n)

    logit = (
        -1.60
        + 1.35 * (care_level == "Independent Living")
        - 0.85 * (care_level == "Skilled Nursing")
        + 0.50 * (tenure_mo < 6)
        - 0.30 * (tenure_mo >= 36)
        - 0.045 * family_visits_month
        - 0.10 * satisfaction_score
        + 0.012 * distance_to_family_mi
        - 0.008 * activity_participation_pct
        + 0.10 * emergency_calls_ytd
        + rng.normal(0, 0.55, size=n)
    )
    departed = np.where(_bernoulli(rng, logit), "Yes", "No")

    ltv = _make_clv(
        rng, tenure_mo, monthly_fee,
        bonus=30.0 * family_visits_month + 8.0 * satisfaction_score,
        additive_noise_sd=650.0,
    )

    return pd.DataFrame(
        {
            "Resident_ID#": _ids(n, "MSL"),
            "Tenure(mo)": tenure_mo,
            "Care_Level": care_level,
            "Monthly_Fee$": monthly_fee,
            "Room_Type#": room_type,
            "Meals_Included_(per_day)": meals_included,
            "Family_Visits/Month": family_visits_month,
            "Has_Companion_Pet?": np.where(has_companion_pet, "Yes", "No"),
            "Activity_Participation_%": activity_participation_pct,
            "Emergency_Calls_YTD#": emergency_calls_ytd,
            "Distance_to_Family_(mi)": distance_to_family_mi,
            "Satisfaction_Score_(1-10)": satisfaction_score,
            "Est_LTV": ltv,
            "Departed?": departed,
        }
    )


COMPANIES = [
    ("vantage-legal-services.csv", make_vantage_legal),
    ("ridgeline-outdoor-gear-club.csv", make_ridgeline_outdoor),
    ("beacon-home-security.csv", make_beacon_security),
    ("thornfield-pet-insurance.csv", make_thornfield_pet_insurance),
    ("meadowbrook-senior-living.csv", make_meadowbrook_senior_living),
]

# (filename, target_column, positive_value) - used by __main__'s sanity
# printout below; target_column/positive_value vary per company (Thornfield
# is deliberately not "Yes"/"No" - see make_thornfield_pet_insurance()).
TARGET_INFO = {
    "vantage-legal-services.csv": ("Left Firm", "Yes"),
    "ridgeline-outdoor-gear-club.csv": ("churn", "yes"),
    "beacon-home-security.csv": ("cancelled", "Yes"),
    "thornfield-pet-insurance.csv": ("Status", "Lapsed"),
    "meadowbrook-senior-living.csv": ("Departed?", "Yes"),
}

# (duration_column, revenue_column, clv_column) - used by __main__'s
# leakage-correlation check below: _make_clv() is designed to NOT be a
# near-deterministic function of duration*revenue (unlike Telco's own real
# TotalCharges, correlation 0.9996 with tenure*MonthlyCharges - the exact
# leak shape src/models/survival.py's DURATION_LEAKAGE_AUTO_DETECT_THRESHOLD
# (0.9) exists to catch), but that's a property of the noise parameters
# chosen per company, not something to just assert - so it's actually
# checked here against the same real threshold, for every company, not
# left as an unverified claim.
LEAKAGE_CHECK_COLUMNS = {
    "vantage-legal-services.csv": ("Months as Client", "Monthly Retainer Fee", "Estimated Lifetime Client Value"),
    "ridgeline-outdoor-gear-club.csv": ("mo_active", "sub_fee", "ltv_est"),
    "beacon-home-security.csv": ("monthsActive", "monthlyFee", "estimatedValue"),
    "thornfield-pet-insurance.csv": ("policy_age_mo", "PREMIUM", "est_lifetime_val"),
    "meadowbrook-senior-living.csv": ("Tenure(mo)", "Monthly_Fee$", "Est_LTV"),
}
DURATION_LEAKAGE_AUTO_DETECT_THRESHOLD = 0.9  # mirrors src/models/survival.py's own real threshold


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(SEED)

    for filename, make_fn in COMPANIES:
        df = make_fn(rng)
        path = OUT_DIR / filename
        df.to_csv(path, index=False)
        target_col, positive_value = TARGET_INFO[filename]
        positive_rate = (df[target_col] == positive_value).mean()

        duration_col, revenue_col, clv_col = LEAKAGE_CHECK_COLUMNS[filename]
        product = df[duration_col] * df[revenue_col]
        clv_correlation = product.corr(df[clv_col])
        assert clv_correlation < DURATION_LEAKAGE_AUTO_DETECT_THRESHOLD, (
            f"{filename}: {clv_col} correlates at {clv_correlation:.4f} with {duration_col}*{revenue_col} - "
            f"at or above the {DURATION_LEAKAGE_AUTO_DETECT_THRESHOLD} leakage threshold; noise parameters "
            "need adjusting before this file is demo-safe."
        )

        print(
            f"{filename}: {len(df):,} rows, {len(df.columns)} columns, "
            f"{target_col}={positive_value!r} rate {positive_rate:.1%}, "
            f"clv-vs-duration*revenue correlation {clv_correlation:.4f} -> {path}"
        )


if __name__ == "__main__":
    main()
